
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>yaf</title>
  <link rel="stylesheet" href="css/app.css">
</head>

<body>
  <div style="display: flex; flex-direction: column; height: 100%">
    <div class="header">站修质检</div>
    <div id="app" style="display: flex; flex-grow: 1; background-color: white">
      <side-menu :menu="menu" :selection="selection" @select="menuSelect"></side-menu>
      <router-view style="flex-grow: 1"></router-view>
    </div>
    <div class="footer">上海申卡数字科技有限公司</div>
  </div>
  <script src="js/manifest.js"></script>
  <script src="js/vendor.js"></script>
  <script src="js/main.js"></script>
</body>
</html>
