<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>yaf</title>
  <link rel="stylesheet" href="css/app.css">
</head>
<body>
  <div id="app" style="display: flex; flex-direction: column; height: 100%">
    <div class="header">站修质检
      <menu></menu>
    </div>
    <router-view style="background-color: #bdb; flex-grow: 1"></router-view>
    <div class="footer">联系电话: 021-51244254</div>
    <message ref="message"></message>
  </div>
  <div id="loading" class="mask" style="display: none">
    <div class="loading">
      <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
    </div>
  </div>
  <script src="js/manifest.js"></script>
  <script src="js/vendor.js"></script>
  <script src="js/main.js"></script>
</body>
</html>
